### ISSUE TITLE
Exporter script supported in AE CC 2015.3?

### ISSUE THREAD

**Issue by therealsalih** [facebookincubator/Keyframes#28] opened 2016-11-22 19:19 UTC
Im attempting to export using the exporter. I selected a comp, pressed "Export" and it is frozen on this:
 
<img width="400" alt="screen shot 2016-11-22 at 11 18 53 am" src="https://cloud.githubusercontent.com/assets/5893643/20538309/7a0bb824-b0a5-11e6-960f-95ec46320c9f.png">

and yes "Allow Scripts to Write Files..." is checked

**Comment by subtleGradient** [comment] 2016-11-22 19:30
That step can take a while depending on how complex your animation is. It's
never really fast

**Comment by therealsalih** [comment] 2016-11-22 19:32
I only have 3 layers & 7 keyframes... and it's been going 30 minutes ☹️ 

<img width="901" alt="screen shot 2016-11-22 at 11 31 35 am" src="https://cloud.githubusercontent.com/assets/5893643/20538731/41c27dc0-b0a7-11e6-8d89-a720f3d697cf.png">

i'll keep trying 💪

**Comment by subtleGradient** [comment] 2016-11-22 22:34
Yeah, that's probably broken. I have some improvements to these scripts that I haven't landed yet. I'll get them landed soon. Hopefully that'll fix this.

Keep me posted if you get this working or if this issue keeps happening.

**Comment by duckinferno** [comment] 2016-11-23 03:52
We're having this issue too - CC 2015.0.  Just hangs on exporting.  This is with a simple drawn shape we made move around a composition.

Somewhat related - do you have any examples or samples of a comp which should work?

**Comment by devvvshin** [comment] 2016-11-23 13:38
me too. I just have 1 layer & 1 keyframe (global scale). but exporting was not worked

**Comment by pfeiffer** [comment] 2016-11-23 13:47
I'm seeing the same. Simple composition, but stuck on 'Exporting' for about an hour.

**Comment by jayleeee** [comment] 2016-11-23 14:03
Me too. I use 2015.3(Mac) version currently, It does not run on 'exporting'.

**Comment by jayleeee** [comment] 2016-11-23 14:09
Me too. I use 2015.3(Mac) version currently, It does not run on 'exporting'.

**Comment by fandy** [comment] 2016-11-23 17:55
I'm having the same issue on CC2017

**Comment by daveobrien-EB** [comment] 2016-11-23 18:05
Works fine for me on CC 2017 14.0.1.5 however the script does not export when working within a team project.

**Comment by subtleGradient** [comment] 2016-11-23 18:27
Poot. I'll get that updated script up there ASAP. But that may be Monday.
Busy week. Sorry about that.

The new script has been tested on Windows 10 with AE 2017 and macOS with AE
2015.2

**Comment by lozzle** [comment] 2016-11-23 22:16
@duckinferno here's a sample working composition of the logo in our sample app: https://github.com/facebookincubator/Keyframes/pull/35/files

once we merge that PR you should have access to it in the master.  i also re-ran the export and updated the json under android/keyframes-sample

we'll take a look at compatibility issues that some of y'all are facing

**Comment by duckinferno** [comment] 2016-11-23 22:50
Hey thanks lozzle, we'll give it a stab :)

**Comment by jayleeee** [comment] 2016-11-24 01:09
Anyone having this error on window(ver.2015.2)? -> 'Unable to execute script at line 87. Uncaught JavaScript exeption: TypeError: cannot convert to C:/.../keyframes/AEcompToKeyframesAnimation.js'

**Comment by NathanWalker** [comment] 2016-11-25 07:00
@subtleGradient Thanks for the work here! I am also experiencing the Export hang in After Effects (2017 release) Version 14.0.1.5 on Mac.

If you know anything I can try in the scripts to get it to work, lemme know and I could try some things and submit a PR to help get this working again.

**Comment by ectoplasMJ** [comment] 2016-11-26 16:19
Same here. Im using ae 2017 (windows)

**Comment by therealsalih** [comment] 2016-11-28 22:49
I'm not sure what happened, but I tried again today and the script magically works now... 👍

No clue what I did, if anything...

**Comment by fandy** [comment] 2016-11-29 12:47
Script is still frozen for me :(

**Comment by mohamede1945** [comment] 2016-11-29 14:52
For people facing this issue here are the steps that fixed it for me:

1. Make sure the file is saved locally to a specific location.
2. Check the settings for **Enabling scripts to write to disk**.
>By default scripts are not allowed to write files or send or receive communication over a network. To allow scripts to write files and communicate over a network, choose Edit > Preferences > General (Windows) or After Effects > Preferences > General (Mac OS), and select the Allow Scripts To Write Files And Access Network option.
3. Restart After Effects.

**Comment by markjeschke** [comment] 2016-11-30 19:38
The script was freezing for me until I followed @mohamede1945's step 1, which was to save the After Effects project as a new copy, locally. If you simply open it up from the downloaded sample folder, you'll get the frozen script.

**Comment by C-M-San** [comment] 2016-12-08 19:47
I have done all the recommended steps above and the script is still stuck on 'exporting' for me.  AE CC 2017.  Anyone make it work with a different method?

**Comment by robinandersen** [comment] 2016-12-12 22:04
The script is stuck for me as well (AE CC 2017) –– All I get is a empty "keyframes.aep.comp-1-Comp 1.log" file.  (I have followed all the steps above.) I want this to work so bad! :)

**Comment by NathanWalker** [comment] 2016-12-13 00:04
Still stuck here as well :(  I'm holding off buying a subscription to aftereffects until I can confirm this is working because this is the only thing that I need working for a particular project with aftereffects.

**Comment by Audiobrad** [comment] 2016-12-13 21:55
I was having the same issue using the script in AE CC 2017 on a mac. I was able to get it working after updating my OS to Sierra.

**Comment by LazyChild** [comment] 2016-12-13 23:14
Added a command line tool (OS X only) [here](https://github.com/facebookincubator/Keyframes/tree/master/scripts#1-command-line-interface)

If you are stucked in the UI, maybe give it a try.

**Comment by leeyc09** [comment] 2017-01-03 07:37
#93 try this.

**Comment by subtleGradient** [comment] 2017-01-11 19:58
Sorry for all the instability until now.
Try the latest version here: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

Let me know if this still gives you any problems.

**Comment by subtleGradient** [comment] 2017-01-19 22:20
The changes have landed in master now.

**Closed** 2017-01-19 22:20 UTC
Labels: bug
