### ISSUE TITLE
Doesn't work on AE CC 2015(Windows)?

### ISSUE THREAD

**Issue by wang9262** [facebookincubator/Keyframes#68] opened 2016-12-13 08:11 UTC
After importing the Scripts to AE, an alert poped up when pressed the "Export" button，showing as below

![1167aa40e7ef1aa468ef4c3708c656f1](https://cloud.githubusercontent.com/assets/5634225/21132078/29c3bcc8-c14d-11e6-84b3-856fe793c73f.png)

some of my configuration:

<img width="745" alt="1167aa40e7ef1aa468ef4c3708c656f11" src="https://cloud.githubusercontent.com/assets/5634225/21132396/b7a1c35e-c14e-11e6-8f9e-b59cafc3bccb.png">
<img width="848" alt="0187f9b5738f5cfd22ceb4e1a8bf642d1" src="https://cloud.githubusercontent.com/assets/5634225/21132397/b971e52e-c14e-11e6-976a-7f65d094137b.png">

 
Any ideas?

**Comment by lozzle** [comment] 2016-12-16 19:54
Likely a dupe of https://github.com/facebookincubator/Keyframes/issues/28

**Closed by lozzle** 2016-12-16 19:54 UTC
